#ifndef MAIN_SDKCONFIG_H
#define MAIN_SDKCONFIG_H



#define CONFIG_RADIO_CHANNEL 90
#define CONFIG_MISO_GPIO 39
#define CONFIG_MOSI_GPIO 38
#define CONFIG_SCLK_GPIO 41
#define CONFIG_CE_GPIO   40
#define CONFIG_CSN_GPIO  37
#define HOST_ID             SPI2_HOST


#endif // MAIN_SDKCONFIG_H
